### ISSUE TITLE
Misannotation on NCBI

### ISSUE THREAD

**Issue by jfouret** [ilya-kolpakov/anaic-analysis#1]
From NCBI I got the following annotation (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE191176):

- GSM5740432_S2 	Infected Untreated
- GSM5740433_S3 	Infected + 6'SLN-CD
- GSM5740434_S4 	Infected + IFN lambda
- GSM5740435_S5 	Infected + 6'SLN-CD + IFN lambda
- GSM5740436_S1 	Mock Steady State
- GSM5740437_S6 	Mock + 6'SLN-CD + IFN lambda

I suppose the right thing is:

- GSM5740436_S1     Infected Untreated
- GSM5740432_S2 	Infected + 6'SLN-CD
- GSM5740433_S3 	Infected + IFN lambda
- GSM5740434_S4 	Infected + 6'SLN-CD + IFN lambda
- GSM5740435_S5 	Mock Steady State
- GSM5740437_S6 	Mock + 6'SLN-CD + IFN lambda

**Comment by 1pakch** [comment]
Hi Julien, thank you for your question.

I am on holidays until the 18th and can't look in detail until then but the correspondence between the conditions and the sample numbers (S1 etc.) looks good to me in the first list you posted (can't say for GSM numbers).

Why do you think the samples are misannotated if I may ask?

**Comment by jfouret** [comment]
Hi Ilya,

Thank you for your reply and sorry for the lack of context,

I was just doing some tests on working with single seq datasets. I chose a public dataset based on the mucilair model since I have some colleagues working with the same model.

![image](https://github.com/1pakch/anaic-analysis/assets/30047021/c5127635-3b41-4582-9160-5b14927988d0)

At first, I picked the supposedly Mock sample GSM5740436 (as shown above a screenshot from NCBI). First thing I did was to plot the percentage of Influenza genes.  however, I had a high percentage of counts on Influenza. And finally when I looked at all the samples I got the figure below. 

![Sans titre](https://github.com/1pakch/anaic-analysis/assets/30047021/a821cbf7-a690-40d2-84da-5206ab33bd02)

Based on this figure I would associate the Mock samples to GSM5740435_S5  and GSM5740437_S6 rather to GSM5740436_S1 and GSM5740437_S6.

For the code: 
https://github.com/nexomis/single-cell-hAE-example/blob/main/fetch_samples.ipynb

Have nice holidays !

**Comment by 1pakch** [comment]
I double-checked the sample labels on GEO and there is a indeed an issue. The correct labels are exactly as you specified, namely:

- GSM5740432_S2: Infected + 6'SLN-CD
- GSM5740433_S3: Infected + IFN lambda
- GSM5740434_S4: Infected + 6'SLN-CD + IFN lambda
- GSM5740435_S5: Uninfected untreated (mock steady state)
- GSM5740436_S1: Infected untreated
- GSM5740437_S6: Uninfected + 6'SLN-CD + IFN lambda

So you were absolutely right and thank you for spotting the problem. I will try to correct the labels on GEO as well.

**Comment by 1pakch** [comment]
I contacted the NCBI about the issue and believe that the error was on their side because the submission form looks good.

**Comment by 1pakch** [comment]
The metadata was corrected on GEO.
